module.exports = {
    AutoEmptyDockManualTriggerCapabilityMqttHandle: require("./AutoEmptyDockManualTriggerCapabilityMqttHandle"),
    BasicControlCapabilityMqttHandle: require("./BasicControlCapabilityMqttHandle"),
    CleanRouteControlCapabilityMqttHandle: require("./CleanRouteControlCapabilityMqttHandle"),
    CapabilityMqttHandle: require("./CapabilityMqttHandle"),
    CarpetModeControlCapabilityMqttHandle: require("./CarpetModeControlCapabilityMqttHandle"),
    CarpetSensorModeControlCapabilityMqttHandle: require("./CarpetSensorModeControlCapabilityMqttHandle"),
    ConsumableMonitoringCapabilityMqttHandle: require("./ConsumableMonitoringCapabilityMqttHandle"),
    CurrentStatisticsCapabilityMqttHandle: require("./CurrentStatisticsCapabilityMqttHandle"),
    GoToLocationCapabilityMqttHandle: require("./GoToLocationCapabilityMqttHandle"),
    KeyLockCapabilityMqttHandle: require("./KeyLockCapabilityMqttHandle"),
    LocateCapabilityMqttHandle: require("./LocateCapabilityMqttHandle"),
    MapSegmentationCapabilityMqttHandle: require("./MapSegmentationCapabilityMqttHandle"),
    MopDockCleanManualTriggerCapabilityMqttHandle: require("./MopDockCleanManualTriggerCapabilityMqttHandle"),
    MopDockDryManualTriggerCapabilityMqttHandle: require("./MopDockDryManualTriggerCapabilityMqttHandle"),
    MultipleMapCapabilityMqttHandle: require("./MultipleMapCapabilityMqttHandle"),
    ObstacleAvoidanceControlCapabilityMqttHandle: require("./ObstacleAvoidanceControlCapabilityMqttHandle"),
    PetObstacleAvoidanceControlCapabilityMqttHandle: require("./PetObstacleAvoidanceControlCapabilityMqttHandle"),
    PresetSelectionCapabilityMqttHandle: require("./PresetSelectionCapabilityMqttHandle"),
    SpeakerPlayAudioCapabilityMqttHandle: require("./SpeakerPlayAudioCapabilityMqttHandle"),
    SpeakerVolumeControlCapabilityMqttHandle: require("./SpeakerVolumeControlCapabilityMqttHandle"),
    TotalStatisticsCapabilityMqttHandle: require("./TotalStatisticsCapabilityMqttHandle"),
    WifiConfigurationCapabilityMqttHandle: require("./WifiConfigurationCapabilityMqttHandle"),
    ZoneCleaningCapabilityMqttHandle: require("./ZoneCleaningCapabilityMqttHandle")
};
